# Generated by Django 5.1.3 on 2025-02-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousey', '0002_forteresse_delete_forteressepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('numero', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reponselevelone',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_level_one', to='mousey.questionlevelone'),
        ),
        migrations.CreateModel(
            name='ReponseLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('est_correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_level_two', to='mousey.questionlevelone')),
            ],
        ),
    ]
